# Numpy

In [1]:
import numpy as np

In [2]:
value_list = [1,2,3,4]

In [6]:
np_arr = np.array(value_list)

In [7]:
np_arr

array([1, 2, 3, 4])

In [8]:
np_arr * 2

array([2, 4, 6, 8])

In [9]:
np_arr / 2

array([0.5, 1. , 1.5, 2. ])

In [10]:
np_arr + np_arr

array([2, 4, 6, 8])

In [11]:
np_arr - np_arr

array([0, 0, 0, 0])

In [12]:
np_arr.mean()

2.5

In [14]:
np_arr.max()

4

In [15]:
np_arr.min()

1

In [16]:
np_arr.std()

1.118033988749895

In [17]:
v1 = np.array([1, 0])
v2 = np.array([0, 1])

In [18]:
v1 + v2

array([1, 1])

In [19]:
v1 - v2

array([ 1, -1])

In [20]:
v1 * v2

array([0, 0])

In [21]:
(v1 * v2).sum()

0

In [23]:
v1.dot(v2)

0

In [33]:
v3 = np.array([1,2])
v4 = np.array([1,4])

In [28]:
v3.dot(v4) #Скалярное произведение

9

In [35]:
v3.shape[0] #размер вектора

2

In [36]:
matrix_list = [[1,2,3], [4,5,6]]

In [37]:
matrix = np.array(matrix_list)

In [38]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
matrix.shape

(2, 3)

In [41]:
 matrix = np.array([[1,2,3],[4,5,6],[8,9,10],[11,12,13]])


In [42]:
matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
matrix[:, :1]

array([[ 1],
       [ 4],
       [ 8],
       [11]])

In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

NameError: name 'np' is not defined

In [46]:
A + B

array([[ 6,  8],
       [10, 12]])

In [47]:
A * B #почленно

array([[ 5, 12],
       [21, 32]])

In [48]:
A.dot(B) #умножение матриц

array([[19, 22],
       [43, 50]])

In [49]:
A * 2

array([[2, 4],
       [6, 8]])

In [50]:
A - 1

array([[0, 1],
       [2, 3]])

In [51]:
A / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [53]:
A_inv = np.linalg.inv(A)

In [55]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
A.dot(np.array([1,2])) #умножение матрицы и вектора

array([ 5, 11])

In [59]:
A.T

array([[1, 3],
       [2, 4]])

In [60]:
np.linalg.solve(np.array([[1,1],[2,-1]]), np.array([7,-11]))

array([-1.33333333,  8.33333333])

In [61]:
vector = np.array([1,2,3,4,5,6])

In [62]:
vector.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

### Pandas

In [1]:
import pandas as pd

In [2]:
#dataFrame

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/nicepeopleproject/ml_linear_regression/master/data/data.csv")

In [4]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [5]:
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
df.head(3).T

0  \
Make                                                 BMW   
Model                                         1 Series M   
Year                                                2011   
Engine Fuel Type             premium unleaded (required)   
Engine HP                                          335.0   
Engine Cylinders                                     6.0   
Transmission Type                                 MANUAL   
Driven_Wheels                           rear wheel drive   
Number of Doors                                      2.0   
Market Category    Factory Tuner,Luxury,High-Performance   
Vehicle Size                                     Compact   
Vehicle Style                                      Coupe   
highway MPG                                           26   
city mpg                                              19   
Popularity                                          3916   
MSRP                                               46135   

                                             1                            2  
Make                                       BMW                          BMW  
Model                                 1 Series                     1 Series  
Year                                      2011                         2011  
Engine Fuel Type   premium unleaded (required)  premium unleaded (required)  
Engine HP                                300.0                        300.0  
Engine Cylinders                           6.0                          6.0  
Transmission Type                       MANUAL                       MANUAL  
Driven_Wheels                 rear wheel drive             rear wheel drive  
Number of Doors                            2.0                          2.0  
Market Category             Luxury,Performance      Luxury,High-Performance  
Vehicle Size                           Compact                      Compact  
Vehicle Style                      Convertible                        Coupe  
highway MPG                                 28                           28  
city mpg                                    19                           20  
Popularity                                3916                         3916  
MSRP                                     40650                        36350

In [7]:
df.MSRP.values #вывод столбца

array([46135, 40650, 36350, ..., 50620, 50920, 28995], dtype=int64)

In [8]:
df['MSRP']

0        46135
1        40650
2        36350
3        29450
4        34500
         ...  
11909    46120
11910    56670
11911    50620
11912    50920
11913    28995
Name: MSRP, Length: 11914, dtype: int64

In [9]:
df['city mpg']

0        19
1        19
2        20
3        18
4        18
         ..
11909    16
11910    16
11911    16
11912    16
11913    17
Name: city mpg, Length: 11914, dtype: int64

In [10]:
df.MSRP.describe().round(2)

count      11914.00
mean       40594.74
std        60109.10
min         2000.00
25%        21000.00
50%        29995.00
75%        42231.25
max      2065902.00
Name: MSRP, dtype: float64

In [11]:
df.Make.unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [14]:
(df.Make.value_counts()/len(df)*100).round(2)

Chevrolet        9.43
Ford             7.39
Volkswagen       6.79
Toyota           6.26
Dodge            5.25
Nissan           4.68
GMC              4.32
Honda            3.77
Mazda            3.55
Cadillac         3.33
Mercedes-Benz    2.96
Suzuki           2.95
BMW              2.80
Infiniti         2.77
Audi             2.75
Hyundai          2.54
Volvo            2.36
Subaru           2.15
Acura            2.12
Kia              1.94
Mitsubishi       1.79
Lexus            1.70
Buick            1.65
Chrysler         1.57
Pontiac          1.56
Lincoln          1.38
Oldsmobile       1.26
Land Rover       1.20
Porsche          1.14
Saab             0.93
Aston Martin     0.78
Plymouth         0.69
Bentley          0.62
Ferrari          0.58
FIAT             0.52
Scion            0.50
Maserati         0.49
Lamborghini      0.44
Rolls-Royce      0.26
Lotus            0.24
Tesla            0.15
HUMMER           0.14
Maybach          0.13
Alfa Romeo       0.04
McLaren          0.04
Spyker    

In [15]:
df.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [23]:
type(dfЫЫ)

pandas.core.frame.DataFrame